runtime: python27
api_version: 1
threadsafe: true
entrypoint: python blog.py

handlers:
- url: /stylesheets 
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /.*
  script: blog.app

